In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import cos, sin, log
from scipy.linalg import solve

In [2]:
n, b, c1,f1=19, 1 ,0, 1
matrx=[[0 for i in range(21)]for j in range(20)]
for i in range(20):
    for j in range(21):
        
        if (i==0)and(j!=20):
            matrx[i][0]=0
            matrx[i][1]=1
            matrx[i][2]=0
        else:
            if (i==19) and (j!=20):
                matrx[i][0]=1
                matrx[i][j]=2
                matrx[i][19]=1
            else:   
                matrx[i][i-1]=1
                matrx[i][i]=-2
                matrx[i][i+1]=1
        if j==20:
            if i==0:
                matrx[0][20]=1
            else:
                if i==19:
                    matrx[19][20]=-19/3
                else:
                    matrx[i][20]=2/((i**2))
                
matrf=np.zeros(20)
for i in range(20):
    for j in range(21):
        matrf[i]=matrx[i][20]
print(matrf)
matr=[[0 for i in range(20)]for j in range(20)]
for i in range(20):
    for j in range(20):
        
        if (i==0)and(j!=20):
            matr[i][0]=0
            matr[i][1]=1
            matr[i][2]=0
        else:
            if (i==19) and (j!=20):
                matr[i][0]=1
                matr[i][j]=2
                matr[i][19]=1
            else:   
                matr[i][i-1]=1
                matr[i][i]=-2
                matr[i][i+1]=1
for i in matr:
    print(i)

[ 1.00000000e+00  2.00000000e+00  5.00000000e-01  2.22222222e-01
  1.25000000e-01  8.00000000e-02  5.55555556e-02  4.08163265e-02
  3.12500000e-02  2.46913580e-02  2.00000000e-02  1.65289256e-02
  1.38888889e-02  1.18343195e-02  1.02040816e-02  8.88888889e-03
  7.81250000e-03  6.92041522e-03  6.17283951e-03 -6.33333333e+00]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0,

In [3]:
matr=[[0 for i in range(20)]for j in range(20)]
for i in range(20):
    for j in range(20):
        
        if (i==0)and(j!=20):
            matr[i][0]=0
            matr[i][1]=1
            matr[i][2]=0
        else:
            if (i==19) and (j!=20):
                matr[i][0]=1
                matr[i][j]=2
                matr[i][19]=1
            else:   
                matr[i][i-1]=1
                matr[i][i]=-2
                matr[i][i+1]=1
for i in matr:
    print(i)
sq=0
sq1=0
for i in range(20):
    for j in range(20):
        sq+=(matr[i][j])**2
AA=sq**(1/2)
print(AA)
matr1=np.linalg.inv(matr)
for i in range(20):
    for j in range(20):
        sq1+=(matr1[i][j])**2
AA1=sq1**(1/2)
print(AA1)
print("Число обуслолвлености:", AA1*AA)

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, 1, 0, 0, 0]
[0, 0, 0,

In [4]:
a=np.zeros(19)
b=np.zeros(19)
c=np.zeros(19)
d=np.zeros(19)
for i in range(1,19):
    a[0]=0
    
    a[i]=1
print(a)
for i in range(1,19):
    b[0]=0
    
    b[i]=-2


print(b)
print(a)
for i in range(19):    
    c[i]=1
    c[18]=0
d=matrf[:-1]
print(c)
print(d)

[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.
 -2.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
[1.         2.         0.5        0.22222222 0.125      0.08
 0.05555556 0.04081633 0.03125    0.02469136 0.02       0.01652893
 0.01388889 0.01183432 0.01020408 0.00888889 0.0078125  0.00692042
 0.00617284]


In [5]:
def norma_nyazki(x, matr, matrf):
    nevyazka=np.dot(a, x)-f
    norma=0
    for elem in nevyazka:
        norma+=elem**2
    return norma**1/2

In [6]:
def thomas_algorithm(a, b, c, d):
    n = len(d)
    # Инициализация прогоночных коэффициентов
    alpha = [0] * n
    beta = [0] * n
    x = [0] * n

    # Прямой ход
    alpha[0] = -c[0] / b[0]
    beta[0] = d[0] / b[0]
    for i in range(1, n):
        alpha[i] = -c[i] / (b[i] + a[i] * alpha[i-1])
        beta[i] = (d[i] - a[i] * beta[i-1]) / (b[i] + a[i] * alpha[i-1])

    # Обратный ход
    x[n-1] = beta[n-1]
    for i in range(n-2, -1, -1):
        x[i] = alpha[i] * x[i+1] + beta[i]

    return x

# Коэффициенты матрицы
a =[0]+ [1] * 18
b = [-2] * 19
c = [1] * 18+[0]

# Вектор правой части
d = [1.0, 2.0, 0.5, 0.2222222222222222, 0.125, 0.08, 0.05555555555555555,
     0.04081632653061224, 0.03125, 0.024691358024691357, 0.02, 0.01652892561983471,
     0.013888888888888888, 0.011834319526627219, 0.01020408163265306, 0.008888888888888889,
     0.0078125, 0.006920415224913495, 0.006172839506172839]
#-6.333333333333333
x_last=0.0
coef=[1, -2, -2,-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, 1]
    
solution = thomas_algorithm(a, b, c, d)
for i in range(19):
    x_last+=solution[i]*coef[i]
x_last=-6.333333333333333/x_last
solution.append(x_last)



In [7]:
def residual_vector(AA, bb, xx):
    A=AA.copy()
    b=bb.copy()
    x=xx.copy()
    n = len(A)
    residual = []
    for i in range(n):
        row_sum = sum(A[i][j] * x[j] for j in range(n))
        residual.append(b[i] - row_sum)
    return residual

residual = residual_vector(matr, matrf, solution)

residual[19]-=159.3612924718122
residual[18]-=0.03998107699850025
residual[0]-=7.246372395440752
itog=0
for i in range(len(residual)):
    itog+=residual[i]


In [8]:
def gaussian_elimination(AA, BB):
    A=AA.copy()
    b=BB.copy()
    n = len(A)
    
    # Прямой ход метода Гаусса
    for i in range(n):
        # Поиск максимального элемента в столбце под диагональю
        max_index = i
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[max_index][i]):
                max_index = j
        # Перестановка строк, если необходимо
        A[i], A[max_index] = A[max_index], A[i]
        b[i], b[max_index] = b[max_index], b[i]
        
        # Приведение матрицы к треугольному виду
        for j in range(i+1, n):
            ratio = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] -= ratio * A[i][k]
            b[j] -= ratio * b[i]
    
    # Обратный ход метода Гаусса
    x = [0] * n
    for i in range(n-1, -1, -1):
        x[i] = b[i] / A[i][i]
        for j in range(i-1, -1, -1):
            b[j] -= A[j][i] * x[i]
    
    return x


solution = gaussian_elimination(matr, matrf)
print("Решение СЛАУ:", solution)

Решение СЛАУ: [3.982445763144322, 0.9999999999999994, 0.0175542368556766, -0.46489152628864616, -0.7251150672107468, -0.8603386081328477, -0.9155621490549483, -0.9152301344214934, -0.8740817932574262, -0.8016834520933591, -0.704593752904601, -0.5875040537158427, -0.4538854289072497, -0.3063779152097679, -0.14703608198565893, 0.02250983287110314, 0.20094463661675407, 0.38719194036240506, 0.5803596593329696, 0.7797002178097069]


In [9]:
lambda_min, lambda_max = np.min(solution), np.max(solution)

print(lambda_min, lambda_max)

-0.9155621490549483 3.982445763144322


In [10]:
res = gaussian_elimination(matr, matrf)
resid = residual_vector(matr, matrf, res)
#print("Вектор невязки:", resid)
itogg=0
for i in range(len(residual)):
    itogg+=resid[i]


In [11]:

print("Величина вектора невязки для Гауса",itogg)
print("Величина вектора невязки для ПВР",itog)

Величина вектора невязки для Гауса 5.724587470723463e-17
Величина вектора невязки для ПВР 5.643749356742944e-14
